version: '2'
services:
  config-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: config-server
    ports:
      - '9101:9101'
    networks:
      - my-network

networks:
  my-network: