version: '2'
services:
  config-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: config-server
    ports:
      - '9101:9101'
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:9101/actuator/health/readiness | grep UP  || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
  eureka-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: eureka-server
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-server:9101
    ports:
      - '9102:9102'
    depends_on:
      config-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:9102/actuator/health/readiness | grep UP || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5