version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - '2181:2181'
  kafka:
    image: wurstmeister/kafka
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_LISTENERS: 'INSIDE://kafka:9093,OUTSIDE://localhost:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT'
      KAFKA_LISTENERS: 'INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
  eureka:
    build:
      context: .
      dockerfile: Dockerfile
    image: eureka
    ports:
      - '9102:9102'
    depends_on:
      - config-server
    networks:
      - my-network
  microservice-product:
    build:
      context: .
      dockerfile: Dockerfile
    image: microservice-product
    ports:
      - '9001:9001'
    depends_on:
      - config-server
    networks:
      - my-network
  microservice-order:
    build:
      context: .
      dockerfile: Dockerfile
    image: microservice-order
    ports:
      - '9002:9002'
    depends_on:
      - config-server
    networks:
      - my-network
  microservice-payment:
    build:
      context: .
      dockerfile: Dockerfile
    image: microservice-payment
    ports:
      - '9003:9003'
    depends_on:
      - config-server
    networks:
      - my-network
  microservice-notification:
    build:
      context: .
      dockerfile: Dockerfile
    image: microservice-notification
    ports:
      - '9004:9004'
    depends_on:
      - config-server
    networks:
      - my-network

networks:
  my-network:
